#This file contains constants translating stats to gold values.
#Each number represents the gold value of one point of that stat.
ATTACKDAMAGE_VALUE = 35
ABILITYPOWER_VALUE = 21.75
ARMOR_VALUE = 20
MR_VALUE = 18
HEALTH_VALUE = 2.67
MANA_VALUE = 1.4
HEALTHREGEN_VALUE = 3
MANAREGEN_VALUE = 5
CRITCHANCE_VALUE = 40
ATTACKSPEED_VALUE = 25
MOVESPEED_VALUE = 12
LIFESTEAL_VALUE = 53.57
PERCENTARMORPEN_VALUE = 41.67
MAGICPEN_VALUE = 31.11
PERCENTMAGICPEN_VALUE = 54.33
ONHITDMG_VALUE = 25
ABILITYHASTE_VALUE = 26.67
PERCENTMOVESPEED_VALUE = 80
HEALSHIELDPOWER_VALUE = 55
OMNIVAMP_VALUE = 39.67
PHYSVAMP_VALUE = 38.58 #estimated
SPELLVAMP_VALUE = 27.5
LETHALITY_VALUE = 29.15